/* eslint-disable no-console */
import { showLogger } from '@/constant/env';

export enum LogType {
  INFO = 'INFO',
  WARN = 'WARN',
  ERROR = 'ERROR',
}

/**
 * A logger function that will only logs on development
 * @param object - The object to log
 * @param comment - Autogenerated with `lg` snippet
 */
export default function logger(object: unknown, type?: LogType): void {
  if (!showLogger) return;

  console.log(`[${type ?? LogType.INFO}] ${object}`);
}
